#! /bin/bash

# load random theme
xrdb ~/.Xresources
THEMENAME=$(shuf -n1 $HOME/.themes/.enabled)
THEME="$HOME/.themes/$THEMENAME"
xrdb -merge "$THEME/colors"

echo "$THEME" > "$HOME/.currenttheme"
cp "$THEME/env" "$HOME/.currentenv"

# fill config templates with theme colors
. $HOME/.scripts/setup-configs

# load theme colors
FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
BACKGROUNDALT=$(xrdb -query | grep 'backgroundAlt:'| awk '{print $NF}')
ALERT=$(xrdb -query | grep 'alert:'| awk '{print $NF}')
ALERTALT=$(xrdb -query | grep 'alertAlt:'| awk '{print $NF}')
WARN=$(xrdb -query | grep 'warn:'| awk '{print $NF}')
HIGHLIGHT=$(xrdb -query | grep 'highlight:'| awk '{print $NF}')
HIGHLIGHTALT=$(xrdb -query | grep 'highlightAlt:'| awk '{print $NF}')

pgrep -x sxhkd > /dev/null || sxhkd &

# bsp config
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          12
bspc config right_padding        12
bspc config left_padding         12
bspc config bottom_padding       12

bspc config split_ratio          0.56
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors  true

# bspwm colors
bspc config normal_border_color   "$BACKGROUNDALT"
bspc config focused_border_color  "$BACKGROUNDALT"
bspc config active_border_color   "$BACKGROUNDALT"
bspc config presel_feedback_color "$ALERT"

# window resizing
bspc config pointer_modifier mod4
bspc config pointer_action1  move
bspc config pointer_action2  resize_corner

bspc rule --add URxvt:ncmpcpp state=floating
bspc rule --add Zathura       state=tiled
bspc rule --add feh           state=floating

## Autostart ##
# load wallpaper according to theme
WALLPAPER=$(shuf -n1 -e $THEME/wallpapers/*)

feh --bg-fill $WALLPAPER
echo $WALLPAPER > "$HOME/.currentbg"

# load neofetch config according to theme
if [ -e "$THEME/neofetch" ]
then
    cat "$THEME/neofetch" > "$HOME/.config/neofetch/config.conf"
else
    cat "$HOME/.config/neofetch/config.default.conf" > "$HOME/.config/neofetch/config.conf"
fi

# set keymap
xmodmap $HOME/.Xmodmap

# change default cursor
xsetroot -cursor_name left_ptr

# set backlight
xbacklight -set 50

# notifications
dunst \
    -lb "$BACKGROUNDALT" -lf "$FOREGROUND" -lfr "$HIGHLIGHTALT" \
    -nb "$BACKGROUNDALT" -nf "$FOREGROUND" -nfr "$WARN" \
    -cb "$BACKGROUNDALT" -cf "$FOREGROUND" -cfr "$ALERT" &

# wifi info & time
sleep 0.2
conky -c "$HOME/.config/conky/conky-wifi.conf" &
sleep 0.2
conky -c "$HOME/.config/conky/conky-clock-2.conf" &
sleep 0.2
conky -c "$HOME/.config/conky/conky-clock-3.conf" &
sleep 0.2
conky -c "$HOME/.config/conky/conky-clock.conf" &

sleep 1
notify-send "bspwm loaded" "with theme $THEMENAME" -u low

sleep 1

# Try to connect to external screen (also starts conky on that screen)
. $HOME/.scripts/screen-connect 


# setup audio & visualization
#mopidy &



