#!/bin/bash

if [ -r "$HOME/.dbus/Xdbus" ]; then
  . "$HOME/.dbus/Xdbus"
fi

if [ $(cat /sys/class/power_supply/BAT1/capacity) -lt 100 ] && [[ $(cat /sys/class/power_supply/BAT1/status) == "Discharging" ]]; then
    /bin/notify-send -u critical "Battery" "Running low on battery :("
fi

    
