#!/bin/bash

if [ $(cat /sys/class/power_supply/BAT1/capacity) -lt 10 ] && [[ $(cat /sys/class/power_supply/BAT1/status) == "Discharging" ]]; then
    if [ -r "$HOME/.dbus/Xdbus" ]; then
	. "$HOME/.dbus/Xdbus"
    fi
    /bin/notify-send -u critical "Battery" "Running low on battery :("
fi

    
