#!/bin/bash

FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
BACKGROUNDALT=$(xrdb -query | grep 'backgroundAlt:'| awk '{print $NF}')
ALERT=$(xrdb -query | grep 'alert:'| awk '{print $NF}')
ALERTALT=$(xrdb -query | grep 'alertAlt:'| awk '{print $NF}')
WARN=$(xrdb -query | grep 'warn:'| awk '{print $NF}')
HIGHLIGHT=$(xrdb -query | grep 'highlight:'| awk '{print $NF}')
HIGHLIGHTALT=$(xrdb -query | grep 'highlightAlt:'| awk '{print $NF}')
HIGHLIGHTFOREGROUND=$(xrdb -query | grep 'highlightForeground:'| awk '{print $NF}')

choice=$(cat $HOME/.themes/.enabled | sort -u \
    | rofi -dmenu -monitor "-1" \
           -hide-scrollbar true \
           -bw 2 \
           -lines 8 \
           -padding 12 \
           -width 32 \
           -location 0 \
           -font "Fantasque Sans Mono 12" \
           -columns 3 \
           -color-enabled true \
           -color-window "$BACKGROUND,$HIGHLIGHTALT,$BACKGROUND" \
           -color-normal "$BACKGROUND,$FOREGROUND,$BACKGROUND,$HIGHLIGHT,$HIGHLIGHTFOREGROUND" \
           -theme-str 'element { highlight: bold; }' \
    )


xrdb $HOME/.Xresources
THEMENAME=$choice
THEME="$HOME/.themes/$THEMENAME"
xrdb -merge "$THEME/colors"

echo "$THEME" > "$HOME/.currenttheme"
cp "$THEME/env" "$HOME/.currentenv"

WALLPAPER=$(shuf -n1 -e $THEME/wallpapers/*)

feh --bg-fill $WALLPAPER
echo $WALLPAPER > "$HOME/.currentbg"

. $HOME/.scripts/setup-configs
