#!/bin/bash

# the screen we want to connect to
NEW_SCREEN="DP-1"
RESOLUTION="3440x1440_48.00"

OLD_SCREEN="eDP-1"

# connect screen
xrandr --output "$NEW_SCREEN" --right-of "$OLD_SCREEN" --mode "$RESOLUTION"

# fix bspwm desktops
bspc monitor "$NEW_SCREEN" -d 1 3 5 7 9
bspc monitor "$OLD_SCREEN" -d 2 4 6 8 0

# kill previous instances of conky
wifipid=$(cat /tmp/conkywifi.pid 2> /dev/null) || "1"
clock1pid=$(cat /tmp/conkyclock1.pid 2> /dev/null) || "1"
clock2pid=$(cat /tmp/conkyclock2.pid 2> /dev/null) || "1"
clock3pid=$(cat /tmp/conkyclock3.pid 2> /dev/null) || "1"

if [ "$(ps -o comm= -p "$wifipid")" = "conky" ]; then
    echo "killed $wifipid"
    kill -9 "$wifipid"
fi

if [ "$(ps -o comm= -p "$clock1pid")" = "conky" ]; then
    echo "killede $clock1pid"
    kill -9 "$clock1pid"
fi

if [ "$(ps -o comm= -p "$clock2pid")" = "conky" ]; then
    echo "killed $clock2pid"
    kill -9 "$clock2pid"
fi

if [ "$(ps -o comm= -p "$clock3pid")" = "conky" ]; then
    echo "killed $clock3pid"
    kill -9 "$clock3pid"
fi

# launch conky on the new desktop
conky -c "$HOME/.config/conky/conky-wifi.conf" -x $((1920+60)) -y 60 &>/dev/null & echo $! > /tmp/conkywifi.pid
disown $(cat /tmp/conkywifi.pid)

conky -c "$HOME/.config/conky/conky-clock.conf" -x $((1920+60)) -y 100 &>/dev/null & echo $! > /tmp/conkyclock1.pid
disown $(cat /tmp/conkyclock1.pid)

conky -c "$HOME/.config/conky/conky-clock-2.conf" -x $((1920+60)) -y 140 &>/dev/null & echo $! > /tmp/conkyclock2.pid
disown $(cat /tmp/conkyclock2.pid)

conky -c "$HOME/.config/conky/conky-clock-3.conf" -x $((1920+60)) -y 180 &>/dev/null & echo $! > /tmp/conkyclock3.pid
disown $(cat /tmp/conkyclock3.pid)
